name: Pull Request Event

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      # - name: Run client.py 
      #   run: python3 client.py 
      - name: Say Hello
        run: echo "hello"

      - name: Run Fibonacci Task (Shell Script)
        run: |
          chmod +x run_fibonacci.sh
          ./run_fibonacci.sh

      # - name: Run process print Task (Shell Script)
      #   run: |
      #     chmod +x print_processes.sh 
      #     ./print_processes.sh

      # - name: Run process print Task (Shell Script)
      #   run: |
      #     chmod +x kill_process.sh 
      #     ./kill_process.sh

      # - name: Run process print Task (Shell Script)
      #   run: |
      #     chmod +x print_history_and_shutdown.sh 
      #     ./print_history_and_shutdown.sh


  # job_2:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Print job ID
  #       run: echo "jobs_2"
  #     - name: sleep2
  #       run: sleep 10

  # job_3:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Print job ID
  #       run: echo "jobs_3"
  #     - name: sleep3
  #       run: sleep 10

  # job_4:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Print job ID
  #       run: echo "jobs_4"
  #     - name: sleep4
  #       run: sleep 10

  # job_5:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Print job ID
  #       run: echo "jobs_5"
  #     - name: sleep5
  #       run: sleep 10


  # job_6:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Print job ID
  #       run: echo "jobs_6"
  #     - name: sleep1
  #       run: sleep 10

  # job_7:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Print job ID
  #       run: echo "jobs_7"
  #     - name: sleep2
  #       run: sleep 10

  # job_8:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Print job ID
  #       run: echo "jobs_8"
  #     - name: sleep3
  #       run: sleep 10

  # job_9:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Print job ID
  #       run: echo "jobs_9"
  #     - name: sleep4
  #       run: sleep 10

  # job_10:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Print job ID
  #       run: echo "jobs_10"
  #     - name: sleep5
  #       run: sleep 10
